name: flutter_spinner_picker
description: Date Picker with spinner instead of a default material time picker. This widget works with 12 or 24 hour format and custom interval mode.
version: 0.0.2
Arthor: hamidjalili
homepage: https://github.com/hamidjalili59/flutter_spinner_picker

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
